# Generated by Django 3.0.3 on 2020-03-16 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email Address')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=100, verbose_name='Name of Business')),
                ('legal_name', models.CharField(max_length=100, verbose_name='Legal Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('business_type', models.CharField(max_length=100, verbose_name='Type of Business')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Contact Name')),
                ('phone_number', models.CharField(help_text='Contact Phone Number', max_length=12)),
                ('website', models.CharField(max_length=30, verbose_name='Website')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('branch_location', models.CharField(help_text='Town', max_length=100, verbose_name='Branch Location')),
                ('aba_number', models.CharField(max_length=100, verbose_name='ABA Number')),
                ('account_number', models.CharField(max_length=100, verbose_name='Account Number')),
                ('banner', models.CharField(choices=[('Please create my banners. I understand there is a cost of $25', 'Please create my banners. I understand there is a cost of $25'), ('No, thank you. I will email you my banners (No Cost). If I do not email you my banners within 5 business days, I authorize you to create the banners for us at the above cost of $25 for both banners.', 'No, thank you. I will email you my banners (No Cost). If I do not email you my banners within 5 business days, I authorize you to create the banners for us at the above cost of $25 for both banners.')], default='No, thank you. I will email you my banners (No Cost). If I do not email you my banners within 5 business days, I authorize you to create the banners for us at the above cost of $25 for both banners.', max_length=1000)),
                ('business_structure', models.CharField(choices=[('Sole Proprietorship', 'Sole Proprietorship'), ('Limited Liability Corporation', 'Limited Liability Corporation'), ('S Corp', 'S Corp'), ('Other', 'Other')], default='Other', max_length=1000)),
                ('length_of_operation', models.CharField(max_length=100, verbose_name='Length of Operation')),
                ('number_of_employees', models.CharField(max_length=100, verbose_name='Number of Employees')),
                ('location_type', multiselectfield.db.fields.MultiSelectField(choices=[('Physical Location', 'Physical Location'), ('Home-based', 'Home-based'), ('Online', 'Online')], max_length=35, verbose_name='Does your business have a physical location? (Check all that apply)')),
                ('speical_business', multiselectfield.db.fields.MultiSelectField(choices=[('Physical Location', 'Physical Location'), ('Home-based', 'Home-based'), ('Online', 'Online')], max_length=35, verbose_name='Is your business: (Check all that apply)')),
                ('tax_credits', models.CharField(choices=[('On line, manually (Free)', 'On line, manually (Free)'), ('Downloading the application onto my own Android (Free)', 'Downloading the application onto my own Android (Free)'), ('Fincredit’s Dedicated Device and Stand ($90)', 'Fincredit’s Dedicated Device and Stand ($90)')], default='On line, manually (Free)', max_length=1000)),
                ('terms_conditions', multiselectfield.db.fields.MultiSelectField(choices=[('AGREE', 'AGREE'), ('DISAGREE', 'DISAGREE')], max_length=14, verbose_name='Terms & Coniditons')),
                ('approved', models.BooleanField(default=False, verbose_name='Application Approved')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
