# Generated by Django 3.0.3 on 2020-03-17 13:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.CharField(choices=[('Please create my banners. I understand there is a cost of $25', 'Please create my banners. I understand there is a cost of $25'), ('No, thank you. I will email you my banners (No Cost). If I do not email you my banners within 5 business days, I authorize you to create the banners for us at the above cost of $25 for both banners.', 'No, thank you. I will email you my banners (No Cost). If I do not email you my banners within 5 business days, I authorize you to create the banners for us at the above cost of $25 for both banners.')], max_length=1000, verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch_location',
            field=models.CharField(max_length=100, verbose_name='Branch Location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_structure',
            field=models.CharField(choices=[('Sole Proprietorship', 'Sole Proprietorship'), ('Limited Liability Corporation', 'Limited Liability Corporation'), ('S Corp', 'S Corp'), ('Other', 'Other')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='speical_business',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Minority Owned', 'Minority Owned'), ('Woman Owned', 'Woman Owned'), ('MWBE Certified', 'MWBE Certified')], max_length=41, verbose_name='Is your business: (Check all that apply)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tax_credits',
            field=models.CharField(choices=[('On line, manually (Free)', 'On line, manually (Free)'), ('Downloading the application onto my own Android (Free)', 'Downloading the application onto my own Android (Free)'), ('Fincredit’s Dedicated Device and Stand ($90)', 'Fincredit’s Dedicated Device and Stand ($90)')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_conditions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AGREE', 'Agree'), ('DISAGREE', 'Disagree')], max_length=14, verbose_name='Terms & Coniditons'),
        ),
    ]
