# Generated by Django 3.0.3 on 2020-03-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200317_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='approved',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3, verbose_name='Application Approved'),
        ),
    ]
