# Generated by Django 3.0.3 on 2020-03-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200317_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aba_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ABA Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch_location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Branch Location'),
        ),
    ]
