# Generated by Django 3.0.3 on 2020-03-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200318_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.CharField(choices=[('Cost to me: 10%, Net Reward to Customer: 7.0%', 'Cost to me: 10%, Net Reward to Customer: 7.0%'), ('Cost to me: 14.3%, Net Reward to Customer: 10%', 'Cost to me: 14.3%, Net Reward to Customer: 10%'), ('Cost to me: 17.1%, Net Reward to Customer: 12%', 'Cost to me: 17.1%, Net Reward to Customer: 12%'), ('Other', 'Other')], default='', max_length=50, verbose_name='Percentage'),
        ),
    ]
