# Generated by Django 3.0.3 on 2020-03-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_rate',
            field=models.CharField(max_length=50, null=True, verbose_name='Other'),
        ),
    ]
