# Generated by Django 3.0.3 on 2020-03-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_other_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='other_rate',
        ),
        migrations.AlterField(
            model_name='user',
            name='length_of_operation',
            field=models.CharField(help_text='Ex: 10', max_length=100, verbose_name='Length of Operation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_of_employees',
            field=models.CharField(help_text='Ex: 12', max_length=100, verbose_name='Number of Employees'),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_conditions',
            field=models.CharField(choices=[('AGREE', 'Agree'), ('DISAGREE', 'Disagree')], default='Agree', max_length=8, verbose_name='Terms & Coniditons'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.CharField(help_text='Ex: www.example.com', max_length=30, verbose_name='Website'),
        ),
    ]
