# Generated by Django 3.0.3 on 2020-04-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200322_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='length_of_operation',
            field=models.CharField(help_text='Ex: 10 months', max_length=100, verbose_name='Length of Operation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_of_employees',
            field=models.CharField(help_text='Ex: 12 employees', max_length=100, verbose_name='Number of Employees'),
        ),
    ]
