# Generated by Django 3.0.3 on 2020-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200522_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.CharField(choices=[('1', 'Cost to me: 10%, Net Reward to Customer: 7.0%'), ('2', 'Cost to me: 14.3%, Net Reward to Customer: 10%'), ('3', 'Cost to me: 17.1%, Net Reward to Customer: 12%'), ('4', 'Other')], default='', max_length=50, verbose_name='Percentage'),
        ),
    ]
