# Generated by Django 3.0.3 on 2020-03-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.CharField(default='', max_length=12, verbose_name='Customer Phone Number'),
        ),
    ]
