# Generated by Django 3.0.3 on 2020-04-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200319_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='options',
            field=models.CharField(default='', max_length=12, verbose_name='Options'),
        ),
    ]
