# Generated by Django 3.0.3 on 2020-04-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='options',
            field=models.CharField(choices=[('None', 'None'), ('Sale', 'Sale'), ('Return', 'Return')], default='Other', max_length=12, verbose_name='Options'),
        ),
    ]
